name: step0 start


# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # read to checkout the repository
  # write to update the step metadata
  contents: write

jobs:
  get_current_step:
    name: check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/script/STEP)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_start:
    name: on start
    needs: get_current_step

    # run when step is 0
    # https://docs.github.com/en/actions/learn-github-actions/contexts
    # https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 0 }}
    runs-on: ubuntu-latest
    steps:
      # check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the branches

      # update README to close <details id=0> and open <details id=1> and set STEP to '1'
      - name: Update to step 1
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          branch_name: module1